In [8]:
import numpy as np

P = np.array([[0.1, 0.3, 0.6], 
              [0.4, 0.2, 0.4], 
              [0.2, 0.5, 0.3]])

In [9]:
P2 = np.matmul(P, P)
print(P2)

[[0.25 0.39 0.36]
 [0.2  0.36 0.44]
 [0.28 0.31 0.41]]


In [11]:
P2 = P@P
print(P2)

[[0.25 0.39 0.36]
 [0.2  0.36 0.44]
 [0.28 0.31 0.41]]


In [15]:
print(P2[0][1])

0.39


In [10]:
P3 = np.matmul(P2, P)
print(P3)

[[0.253 0.333 0.414]
 [0.252 0.352 0.396]
 [0.234 0.351 0.415]]


In [13]:
P3 = P@P@P
print(P3)

[[0.253 0.333 0.414]
 [0.252 0.352 0.396]
 [0.234 0.351 0.415]]
