In [25]:
import random

random.seed(1234567)

random.uniform(1,2)

1.9631432476096222

In [26]:
random.randint(1,10)

4

In [30]:
import numpy as np

np.random.seed(1234567)

x_list = np.random.uniform(low=1, high=2, size=5)
print(x_list)

[1.23702917 1.00764837 1.01983031 1.31309262 1.09945466]


In [31]:
x_list = np.random.randint(low=0, high=1, size=10)
print(x_list)

[0 0 0 0 0 0 0 0 0 0]


In [32]:
x_list = np.random.randint(low=0, high=2, size=10)
print(x_list)

[0 0 1 1 1 0 0 1 1 0]
